name = "video-upload-api"
main = "functions/upload.ts"
compatibility_date = "2024-01-01"
account_id = "09a7ba6e7eae31ff8fdee2255891fa52"

# R2 Bucket 绑定
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "my-r2-nxc"

# 公共访问域名（部署 Worker 后填入）
[vars]
ALLOWED_ORIGINS = "*"
R2_PUBLIC_URL = "https://pub-3300c5431c524c789f6aa30ae9bad4a9.r2.dev"
